version: 2.1

orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4
jobs:
  build_and_deploy_mainnet:
    docker:
      - image: "cimg/node:16.7"
    steps:
      - checkout
      - run:
          name: download & unzip awscli v2
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip
      - run:
          name: install awscli v2
          command: sudo ./aws/install
      - restore_cache:
          key: voltswapv2-deps-{{ checksum "package.json" }}
      - run:
          name: install npm dependencies
          command: npm install
      - save_cache:
          key: voltswapv2-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: delete .next
          command: rm -rf .next
      - run:
          name: production build
          command: npm run build2
      - run:
          name: s3 sync
          command: aws s3 sync ./out/ s3://voltswap.finance/ --delete
      - run:
          name: invalidation
          command: aws cloudfront create-invalidation --distribution-id E2MJ1Y5F1U1W57 --paths "/*"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  fresh_deploy:
    jobs:
      - build_and_deploy_mainnet:
          context:
            - aws-2023
            - slack-secrets
            - swapv2-env
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
